// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxSkIEIikfAHa-LpBPjJ2RUL1CrXhBLAY',
    appId: '1:813285975226:web:ced015d0f1bf1e82b98e83',
    messagingSenderId: '813285975226',
    projectId: 'streaming-plat-49327',
    authDomain: 'streaming-plat-49327.firebaseapp.com',
    storageBucket: 'streaming-plat-49327.firebasestorage.app',
    measurementId: 'G-N15BBG3YR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3DEbr8ET9ibCzKsfYfiBwKn6OSfZuLFA',
    appId: '1:813285975226:android:b40e462ec44b9351b98e83',
    messagingSenderId: '813285975226',
    projectId: 'streaming-plat-49327',
    storageBucket: 'streaming-plat-49327.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARzD8LFOCU-9kcy4dpUapIw1YxXDK2plE',
    appId: '1:813285975226:ios:ce57653109748aecb98e83',
    messagingSenderId: '813285975226',
    projectId: 'streaming-plat-49327',
    storageBucket: 'streaming-plat-49327.firebasestorage.app',
    iosBundleId: 'com.example.streamingplat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARzD8LFOCU-9kcy4dpUapIw1YxXDK2plE',
    appId: '1:813285975226:ios:ce57653109748aecb98e83',
    messagingSenderId: '813285975226',
    projectId: 'streaming-plat-49327',
    storageBucket: 'streaming-plat-49327.firebasestorage.app',
    iosBundleId: 'com.example.streamingplat',
  );
}
